trigger:
  branches:
    include:
      - main  # Ensure the pipeline is triggered when main branch updates on GitHub

resources:
  repositories:
    - repository: gitHub-OrchManager
      type: github
      name: maheshUIPah/OrchestratorManager
      endpoint: GitHub  # GitHub Service Connection in Azure DevOps

steps:
  - checkout: gitHub-OrchManager  # Check out the GitHub repository
  - script: 
      echo "Building the project from GitHub"
