trigger:
  branches:
    include:
      - main  # Ensure the pipeline is triggered when main branch updates on GitHub

pool:
  vmImage: windows-latest

steps:
  - checkout: github-repo  # Check out the GitHub repository
  - script: 
      echo "Building the project from GitHub"
  - task: UiPathPack@4
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: '$(Build.SourcesDirectory)'
      orchestratorConnection: 'Staging_Orchestrator'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      traceLevel: 'Information'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Demo'
      publishLocation: 'Container'